-- Reminder engine — Part 8 Phase 4. Email + SMS reminders at T-7, T-2,
-- T-1 days ahead of each case deadline (feature list §2.3), for both the
-- discount and final deadlines (Part 2.3 says "ahead of each deadline",
-- plural — read literally as both, not just final_deadline).
--
-- Reminder rows are (re)generated by a trigger whenever a case's deadlines
-- change, rather than computed on the fly at send time — this makes "what
-- reminders exist for this case" a queryable, auditable fact, and matches
-- the reminders table Part 5 already specifies (case_id, channel,
-- scheduled_for, sent_at). Actual sending happens out-of-band (Edge
-- Function + pg_cron, per Part 6) — this migration only creates and
-- maintains the schedule, it does not send anything.

create table if not exists reminders (
  id uuid primary key default gen_random_uuid(),
  case_id uuid not null references cases(id) on delete cascade,
  channel text not null check (channel in ('email', 'sms')),
  deadline_type text not null check (deadline_type in ('discount', 'final')),
  scheduled_for timestamptz not null,
  sent_at timestamptz,
  created_at timestamptz not null default now()
);

create index if not exists reminders_case_id_idx on reminders (case_id);
create index if not exists reminders_due_idx on reminders (scheduled_for) where sent_at is null;

alter table reminders enable row level security;

create policy "users who can view the case can view its reminders"
  on reminders for select
  to authenticated
  using (exists (select 1 from cases c where c.id = case_id and can_view_vehicle(c.vehicle_id)));

-- No insert/update/delete policy for authenticated — the schedule is
-- maintained entirely by the trigger below (creation/regeneration) and by
-- the sender Edge Function using the service role (marking sent_at), never
-- directly by a client.

create or replace function regenerate_case_reminders()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  offsets int[] := array[7, 2, 1]; -- days before the deadline
  channels text[] := array['email', 'sms'];
  offset_days int;
  chan text;
begin
  -- Deadlines rarely change once set, but they can (a correction, or OCR
  -- re-run) — drop any not-yet-sent reminders tied to the old dates so the
  -- schedule never drifts from the case's current deadlines. Already-sent
  -- reminders are left alone; they're a record of what actually went out.
  delete from reminders where case_id = new.id and sent_at is null;

  if new.discount_deadline is not null then
    foreach offset_days in array offsets loop
      foreach chan in array channels loop
        if (new.discount_deadline - offset_days) >= current_date then
          insert into reminders (case_id, channel, deadline_type, scheduled_for)
          values (
            new.id, chan, 'discount',
            (new.discount_deadline - offset_days) + time '09:00'
          );
        end if;
      end loop;
    end loop;
  end if;

  if new.final_deadline is not null then
    foreach offset_days in array offsets loop
      foreach chan in array channels loop
        if (new.final_deadline - offset_days) >= current_date then
          insert into reminders (case_id, channel, deadline_type, scheduled_for)
          values (
            new.id, chan, 'final',
            (new.final_deadline - offset_days) + time '09:00'
          );
        end if;
      end loop;
    end loop;
  end if;

  return new;
end;
$$;

revoke execute on function regenerate_case_reminders() from public, anon, authenticated;

drop trigger if exists on_case_deadlines_change on cases;
create trigger on_case_deadlines_change
  after insert or update of discount_deadline, final_deadline on cases
  for each row execute function regenerate_case_reminders();
